### ISSUE TITLE
After I compiled it, I ran the blog.sh file and no .emb file was generated. why is that?

### ISSUE THREAD

**Issue by Doehong** [THU-numbda/SketchNE#1]
+ python predict.py --label ../data/blogcatalog.mat --embedding blog.spec --seed 0 --C 3 --start-train-ratio 10 --stop-train-ratio 90 --num-train-ratio 9 --num-split 5
(10312, 39) bool
Traceback (most recent call last):
  File "predict.py", line 159, in <module>
    embedding = np.fromfile(args.embedding, dtype=np.float32).reshape(-1,args.dim)
FileNotFoundError: [Errno 2] No such file or directory: 'blog.spec'
Obviously the error is reported because the python file cannot read the embbeding file！

**Comment by xyyphant0m** [comment]
So the program is running correctly? Has blog.spec been generated? 
The program is very fast on small data, and blog should not take more than 5 seconds, so you feel that it has not run. 
If you have any questions, you can try a slightly larger example, such as YouTube.

**Comment by Doehong** [comment]
Following the readme, I ran into actually two problems. 1. When making, an error will be reported that the ligra/ligra.h file was not found. This problem was solved after I changed #include "ligra/ligra.h" to #include "ligra.h". 2. After successful make, I encountered an error that the emb file could not be generated correctly. I'm sure the program is not running properly, but there is no error reported. Because the file not only did not generate an emb file, but also ended immediately after running blog.sh. Yes immediately

**Comment by xyyphant0m** [comment]
I just tried running this GitHub code again, everything seems perfectly normal.
<img width="934" alt="image" src="https://github.com/THU-numbda/SketchNE/assets/22081610/18a6fd9f-ed0d-47cb-9783-56354b9788b3">
<img width="873" alt="image" src="https://github.com/THU-numbda/SketchNE/assets/22081610/3d59d893-2315-4bf3-ba3a-7e9745792d25">
You may need to remove "numactl -i all" from blog.sh. If it still does not run, please post a screenshot of the actual runtime so I can see what is happening.

**Comment by Doehong** [comment]
ok,i think i found y it not work.look this plz 

![1](https://github.com/THU-numbda/SketchNE/assets/38686239/e420e4f4-51a2-4097-9173-9e927f2b38e5)
how can i solve this problem?i sure i have install that. the result by find as follow 
![2](https://github.com/THU-numbda/SketchNE/assets/38686239/d50833fc-c5e1-429c-a1fe-3ac115e493d4)

**Comment by Doehong** [comment]
ok,i solve this ,it work perfectly
