### ISSUE TITLE
The blog.sh file failed to run

### ISSUE THREAD

**Issue by 123shiqi** [THU-numbda/SketchNE#2]
When I execute the bash blog.sh command in the example directory, I get the following error:
1.... /sketchne: No such file or directory
2. The blog.spec file cannot be found
![~YF@A8U W$@F NE$))8988](https://github.com/THU-numbda/SketchNE/assets/86699420/c46e49fe-af14-47f9-87c2-483d3b9654f7)
When I try to put... /skechne to... /skechne.cpp, the following error occurs:
![WDDXE_ZC{1JH6MNXN0ZTC{P](https://github.com/THU-numbda/SketchNE/assets/86699420/fc7a3fef-db7c-45a4-9017-9806793f7e13)
I don't know what to do now, so I would like to ask the author to help me answer the question

**Comment by yuyangxie96** [comment]
Please follow the README to compile and generate the ./sketch executable file.  Then you can run blog.sh.

**Comment by yuyangxie96** [comment]
> When I execute the bash blog.sh command in the example directory, I get the following error: 1.... /sketchne: No such file or directory 2. The blog.spec file cannot be found ![~YF@A8U W$@F NE$))8988](https://user-images.githubusercontent.com/86699420/270537877-c46e49fe-af14-47f9-87c2-483d3b9654f7.png) When I try to put... /skechne to... /skechne.cpp, the following error occurs: ![WDDXE_ZC{1JH6MNXN0ZTC{P](https://user-images.githubusercontent.com/86699420/270538134-fc7a3fef-db7c-45a4-9017-9806793f7e13.png) I don't know what to do now, so I would like to ask the author to help me answer the question

Please follow the README to compile and generate the ./sketch executable file. Then you can run blog.sh.

**Comment by yuyangxie96** [comment]
@123shiqi  Please follow the README to compile and generate the ./sketch executable file. Then you can run blog.sh.

**Comment by 123shiqi** [comment]
After the make operation, an error occurred：
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/57241493-6190-4ced-87dc-eb61acd728a0)

**Comment by 123shiqi** [comment]
Looks like more than one mistake
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/4b4055dd-a078-4420-a2f9-cdd01b747daf)

**Comment by yuyangxie96** [comment]
@123shiqi  Please use c++17 in Makefile.

**Comment by 123shiqi** [comment]
Ok, I'll try to modify it now

**Comment by 123shiqi** [comment]
May I ask which step has gone wrong：
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/8a139296-e34b-4d01-8347-fddc1d2dbbd2)

**Comment by yuyangxie96** [comment]
Please carefully perform every step in README. This problem is caused by not specifying the dynamic link library path.
<img width="912" alt="image" src="https://github.com/THU-numbda/SketchNE/assets/22081610/96c313fc-3f4d-44ca-a770-d53ea8e78526">

**Comment by 123shiqi** [comment]
I have achieved this step，but the above error seems to have occurred
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/74caf081-ec74-44f8-a5cb-ba3530d95a92)

**Comment by 123shiqi** [comment]
Sorry, I seem to have successfully run, thank you very much!
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/103d85c6-ce4f-4368-a90a-fb7bb2b957f1)

**Comment by 123shiqi** [comment]
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/c9c88799-ea71-48de-abc7-0163d9cce6ab)
