### ISSUE TITLE
当运行blog.sh后，没有blog.spec和blog.emb生成，但是生成了日志，这是为什么

### ISSUE THREAD

**Issue by 123shiqi** [THU-numbda/SketchNE#3]
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/6c326ca8-3bea-4417-b3d2-e679490e2953)
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/262c40c4-df1d-41a3-af00-71e21d63678d)
我该如何解决上图的问题

**Comment by yuyangxie96** [comment]
no command "/usr/bin/time", just comment it.

**Comment by 123shiqi** [comment]
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/a5503901-25f8-47f2-8408-affe5e250bcd)
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/22958255-191b-4b6d-8ddc-18d666a0e25d)
这样修改对吗

**Comment by 123shiqi** [comment]
Hello, after I delete "/usr/bin/time", the following problem still occurs, how can I solve it
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/aa5582b2-01fb-4a73-8113-779f0f7177db)

**Comment by yuyangxie96** [comment]
check ../sketchne is in the dir? It seems that you may have run "make clean" to delete the executable file.

**Comment by 123shiqi** [comment]
ok, thank you! I've run it successfully. Because I'm following the readme above, every time I do "make "I do "make clean", so the above problem occurs
