### ISSUE TITLE
some Error happen in the eigSVD syev(syevd),info:-5

### ISSUE THREAD

**Issue by 123shiqi** [THU-numbda/SketchNE#4]
Hello, I want to process the MovieLens dataset in the skechne algorithm, so I generate Movielens.mat similar to blog.mat, and then write out the Movielens.sh file modeled after blog.sh. However, after executing the "bash MovieLens.sh" command, the following problem occurs. I see that after blog.sh runs, info seems to have a value of 0, but I don't know why the ifo generated after MovieLens.sh runs is -5. I have read the source code for a long time, and I really don't know where the problem is, so I would like to ask you to guide me.
![image](https://github.com/THU-numbda/SketchNE/assets/86699420/963b9aa1-cdbc-4d05-a547-1eda19ffb0e8)

**Comment by yuyangxie96** [comment]
Suppose the movielens matrix is **_A_**, check if **_A_** has a row or column that is all zeros.

**Comment by 123shiqi** [comment]
Yes, what should I do

**Comment by yuyangxie96** [comment]
@123shiqi  delete the all zero rows or columns and generate the new matrix in .mat
